/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import ccgCustomUiFields from "../../src/plugins/ccg-custom-ui-fields/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "content-versioning": contentVersioning,
    i18n: i18N,
    "ccg-custom-ui-fields": ccgCustomUiFields,
  },
});
