      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}

            # 🟢 Log deployment time
            echo "Deployed from GitHub Actions at $(date)" >> deploy.log

            git fetch --all
            git reset --hard origin/main
            npm ci
            npm run build
            pm2 reload strapi || pm2 start "npm run start" --name strapi
            pm2 save